### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by AkiaCode** [depnoland/denoland_api#1]
`https://api.deno.land/modules?page=1&limit=20&query=e`
`https://cdn.deno.land/rad/meta/versions.json`
`https://cdn.deno.land/std/versions/0.82.0/meta/deps_v2.json`
`https://cdn.deno.land/std/versions/0.82.0/meta/meta.json`
`https://api.deno.land/modules/rad`
`https://cdn.deno.land/<package>/versions/<version>(v5.0.0)/raw/<path>`

**Comment by pmh-only** [comment]
um maybe done

**Comment by AkiaCode** [comment]
` https://doc.deno.land/api/docs?entrypoint=https%3A%2F%2Fgithub.com%2Fdenoland%2Fdeno%2Freleases%2Flatest%2Fdownload%2Flib.deno.d.ts`

**Comment by AkiaCode** [comment]
@pmh-only  Will Work it

**Comment by pmh-only** [comment]
okay
